export default function TermsPage() {
  return (
    <main className="mx-auto flex min-h-screen max-w-2xl flex-col gap-4 p-6 text-sm text-gray-800">
      <h1 className="text-2xl font-semibold text-black">Terms of Service</h1>
      <p className="text-xs text-gray-500">Last updated: 8 July 2026</p>

      <p>
        BondProof (&quot;we&quot;, &quot;us&quot;) provides a document preparation
        and evidence-organisation tool for residential tenants in New South
        Wales. By creating an account or using the service, you agree to
        these terms.
      </p>

      <h2 className="text-lg font-semibold text-black">1. What BondProof is — and isn&apos;t</h2>
      <p>
        BondProof helps you document your rental property&apos;s condition,
        organise photo evidence, and prepare paperwork (condition reports,
        dispute letters, evidence packs, and a pre-filled NCAT application
        form) related to residential tenancy bond disputes in NSW.
      </p>
      <p>
        <strong>BondProof is not a law firm and does not provide legal advice.</strong>{' '}
        Documents generated by the service are drafting assistance only. We
        recommend seeking independent legal advice (for example, from Tenants&apos;
        Union NSW or a solicitor) before lodging an NCAT application or relying
        on generated documents in a dispute.
      </p>

      <h2 className="text-lg font-semibold text-black">2. Your account</h2>
      <p>
        You&apos;re responsible for the accuracy of the information you enter
        (tenancy details, claimed amounts, photos) and for keeping your login
        secure. One free account may have one active tenancy at a time.
      </p>

      <h2 className="text-lg font-semibold text-black">3. Pricing</h2>
      <p>
        Entry capture, the evidence vault, and the entry condition report are
        free. The Dispute Kit (exit comparison, evidence pack, response
        letter, NCAT pre-fill, and deadline tracking) is a one-off paid
        purchase, charged once per tenancy via Stripe. Prices are shown in
        Australian dollars at checkout and are non-refundable once the
        Dispute Kit documents have been generated, except where required by
        Australian Consumer Law.
      </p>

      <h2 className="text-lg font-semibold text-black">4. Accuracy of generated documents</h2>
      <p>
        Response letters are drafted by an AI model constrained to the
        evidence you&apos;ve captured in the app. You&apos;re responsible for
        reviewing every generated document — including the pre-filled NCAT
        form — for accuracy before sending or lodging it. We don&apos;t
        guarantee any particular outcome from a dispute or NCAT application.
      </p>

      <h2 className="text-lg font-semibold text-black">5. Your content</h2>
      <p>
        You retain ownership of the photos and information you upload. You
        grant us a licence to store and process it solely to provide the
        service to you (generating reports, comparisons, and documents). See
        our <a className="underline" href="/legal/privacy">Privacy Policy</a>{' '}
        for how we handle your data, including export and deletion.
      </p>

      <h2 className="text-lg font-semibold text-black">6. Limitation of liability</h2>
      <p>
        To the maximum extent permitted by law, BondProof is provided
        &quot;as is&quot; without warranties of any kind. We are not liable
        for the outcome of any bond dispute, NCAT proceeding, or decision you
        make based on documents generated by the service. Nothing in these
        terms excludes rights you have under the Australian Consumer Law that
        cannot be excluded.
      </p>

      <h2 className="text-lg font-semibold text-black">7. Changes</h2>
      <p>
        We may update these terms from time to time. Continued use of the
        service after a change means you accept the updated terms.
      </p>

      <h2 className="text-lg font-semibold text-black">8. Governing law</h2>
      <p>These terms are governed by the laws of New South Wales, Australia.</p>

      <p className="mt-4 text-xs text-gray-500">
        This is a draft template and has not been reviewed by a solicitor.
        Have it reviewed before relying on it commercially.
      </p>
    </main>
  )
}
